spring.application.name=interview-prep-backend

spring.datasource.url=jdbc:mysql://localhost:3306/interview_prep
spring.datasource.username=root
spring.datasource.password=ajay@891

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
